name: チェック用のプルリクエストを作成
on:
  push:
    branches:
      - develop
jobs:
  create_pr_checked_job:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
    name: チェック用のプルリクエストを作成
    steps:
      - name: チェックアウト
        uses: actions/checkout@v2
      - name: npmインストール
        run: npm ci
      - name: create-check-pr
        uses: ./.github/actions/create-pr-checked
        with:
          base: main
          head: develop
          token: ${{ secrets.GITHUB_TOKEN }}
